name: Salesforce Code Analyzer Workflow
on: workflow_dispatch
jobs:
  salesforce-code-analyzer-workflow:
    runs-on: self-hosted
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      # - name: Install Salesforce CLI
      #   run: npm install -g @salesforce/cli@latest

      # - name: Install Salesforce Code Analyzer Plugin
      #   run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results
